# docker-compose.yml
version: '3.8'

services:
  db:
    image: mysql:8
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=mydatabase
      - MYSQL_ROOT_HOST=%
  web:
    build: ./backend
    volumes:
      - static_volume:/app/static
    ports:
      - 8000:8000
    environment:
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=admin
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - static_volume:/app/static
    depends_on:
      - web
  swagger_ui:
    image: swaggerapi/swagger-ui
    ports:
      - 8080:8080
    volumes:
      - ./backend/api_schema.yml:/app/api_schema.yaml
    environment:
      SWAGGER_JSON: /app/api_schema.yaml

volumes:
  mysql_data:
  static_volume:
